{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "storage.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "storage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "storage.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "storage.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      securityContext: {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      initContainers: []
      containers:
        - name: {{ include "storage.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-jwt
                  key: anonKey
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-jwt
                  key: serviceKey
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-jwt
                  key: secret
            - name: POSTGREST_URL
              value: "http://{{ include "rest.fullname" . }}:3000"
            - name: FILE_SIZE_LIMIT
              value: "52428800"
            - name: STORAGE_BACKEND
              value: file
            - name: FILE_STORAGE_BACKEND_PATH
              value: /var/lib/storage
            - name: TENANT_ID
              value: stub
            - name: REGION
              value: stub
            - name: GLOBAL_S3_BUCKET
              value: stub
            - name: ENABLE_IMAGE_TRANSFORMATION
              value: "true"
            - name: IMGPROXY_URL
              value: "http://{{ include "imgproxy.fullname" . }}:5001"
            - name: REQUEST_ALLOW_X_FORWARDED_PATH
              value: "true"
            - name: DB_HOST
              value: {{ .Values.dbHost | default (printf "%s-db" .Release.Name) | quote }}
            - name: DB_PORT
              value: {{ .Values.dbPort | default "5432" | quote }}
            - name: DB_NAME
              value: {{ .Values.dbName | default "postgres" | quote }}
            - name: DATABASE_URL
              value: "postgres://supabase_storage_admin:$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-db
                  key: password
          {{- with .Values.deployment.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: storage-data
              mountPath: /var/lib/storage
            {{- with .Values.deployment.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.lifecycle }}
          lifecycle: {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: {{ include "storage.fullname" . }}-data
        {{- with .Values.deployment.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
