annotations:
  catalog.cattle.io/release-name: mysql
apiVersion: v2
name: mysql
version: 8.0.0
icon: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/mysql/mysql-original.svg
appVersion: "8.0"
description: A Helm chart for MySQL Database
keywords:
  - mysql
  - database
home: https://www.mysql.com/
sources:
  - https://github.com/mysql/mysql-server
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@126.com