annotations:
  catalog.cattle.io/release-name: elasticsearch
apiVersion: v2
name: elasticsearch
version: 2.0.11
description: A Helm chart for deploying the elasticsearch application
type: application
keywords:
  - elasticsearch
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@126.com
icon: https://img0.baidu.com/it/u=2447772143,1405976340&fm=253&fmt=auto&app=138&f=JPEG?w=751&h=500
appVersion: "8.17.3"
