{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "storage.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "storage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "storage.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "storage.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      securityContext: {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      initContainers:
        - name: init-db
          image: "{{ .Values.initDbImage.repository }}:{{ .Values.initDbImage.tag }}"
          imagePullPolicy: {{ .Values.initDbImage.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.dbHost | default (printf "%s-db" .Release.Name) | quote }}
            - name: DB_PORT
              value: {{ .Values.dbPort | default "5432" | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h $(DB_HOST) -p $(DB_PORT) -U postgres; do
              echo "Waiting for database to start..."
              sleep 2
              done
            - echo "Database is ready"
      containers:
        - name: {{ include "storage.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: DB_USER
              value: {{ .Values.environment.DB_USER | quote }}
            - name: DB_DRIVER
              value: {{ .Values.environment.DB_DRIVER | quote }}
            - name: DB_SSL
              value: {{ .Values.environment.DB_SSL | quote }}
            - name: PGOPTIONS
              value: {{ .Values.environment.PGOPTIONS | quote }}
            - name: FILE_SIZE_LIMIT
              value: {{ .Values.environment.FILE_SIZE_LIMIT | quote }}
            - name: STORAGE_BACKEND
              value: {{ .Values.environment.STORAGE_BACKEND | quote }}
            - name: GLOBAL_S3_PROTOCOL
              value: {{ .Values.environment.GLOBAL_S3_PROTOCOL | quote }}
            - name: GLOBAL_S3_ENDPOINT
              value: {{ .Values.environment.GLOBAL_S3_ENDPOINT | quote }}
            - name: GLOBAL_S3_FORCE_PATH_STYLE
              value: {{ .Values.environment.GLOBAL_S3_FORCE_PATH_STYLE | quote }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.environment.AWS_DEFAULT_REGION | quote }}
            - name: FILE_STORAGE_BACKEND_PATH
              value: {{ .Values.environment.FILE_STORAGE_BACKEND_PATH | quote }}
            - name: TENANT_ID
              value: {{ .Values.environment.TENANT_ID | quote }}
            - name: REGION
              value: {{ .Values.environment.REGION | quote }}
            - name: ENABLE_IMAGE_TRANSFORMATION
              value: {{ .Values.environment.ENABLE_IMAGE_TRANSFORMATION | quote }}
            - name: IMGPROXY_URL
              value: {{ .Values.environment.IMGPROXY_URL | quote }}
            - name: ENABLE_QUEUE_EVENTS
              value: {{ .Values.environment.ENABLE_QUEUE_EVENTS | quote }}
            {{- if .Values.dbHost }}
            - name: DB_HOST
              value: {{ .Values.dbHost | quote }}
            {{- end }}
            {{- if .Values.dbPort }}
            - name: DB_PORT
              value: {{ .Values.dbPort | quote }}
            {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-db
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-db
                  key: database
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-jwt
                  key: secret
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-jwt
                  key: anonKey
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-jwt
                  key: serviceKey
            - name: GLOBAL_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-s3
                  key: accessKey
            - name: GLOBAL_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-s3
                  key: secretKey
          {{- with .Values.deployment.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.lifecycle }}
          lifecycle: {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
      {{- with .Values.deployment.volumes }}
      volumes: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
