# yaml 配置实例
version: '3.8'
# 统一在cloud下
networks:
  cloud:
    driver: bridge
    name: cloud
services:
  mysql:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - cloud
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    restart: "always"
    container_name: mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - cloud
    container_name: redis
  importSql:
    image: "swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/alpine:3.20.3"
    command: |
      /bin/sh -c "
      sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories &&
      apk add --no-cache mysql-client &&
      mkdir -p /opt &&
      cd /opt &&
      wget --no-check-certificate https://gitee.com/jiapengCode/snowy-cloud/raw/dev-jp/snowy-server/snowy-nacos-app/src/main/resources/META-INF/nacos-db.sql -O 1_nacos-db.sql &&
      wget --no-check-certificate https://gitee.com/jiapengCode/snowy-cloud/raw/dev-jp/snowy-server/snowy-nacos-app/src/main/resources/META-INF/nacos-db-snowy-config-init.sql -O 2_nacos-db-snowy-config-init.sql &&
      wget --no-check-certificate https://gitee.com/jiapengCode/snowy-cloud/raw/dev-jp/snowy-server/snowy-xxl-job-app/src/main/resources/db/tables_xxl_job.sql -O 3_xxl-job.sql &&
      wget --no-check-certificate https://gitee.com/jiapengCode/snowy-cloud/raw/master/snowy-modules/snowy-web-app/src/main/resources/_sql/snowy_cloud_mysql.sql -O 4_snowy_cloud_mysql.sql &&
      echo 'SET FOREIGN_KEY_CHECKS=0;' > /opt/snowy_cloud_mysql.sql &&
      sed -i '1i-- -------------------------\n -- snowy-cloud 不存在则创建 \n-- ---------------------------\n create database IF NOT EXISTS `snowy-cloud` default character set utf8mb4 COLLATE utf8mb4_general_ci; \n use `snowy-cloud`;' 4_snowy_cloud_mysql.sql &&
      echo 'mysql 连接中'
      for sql_file in $$(ls /opt/*.sql); do
        echo '执行sql文件：$$sql_file';
        chmod 777 $$sql_file;
        ls -lh $$sql_file;
        if [[ $$sql_file =~ 'nacos' || $$sql_file =~ 'config' ]]; then
          # sed -i 's/jdbc:mysql:\/\/127.0.0.1:3306/jdbc:mysql:\/\/mysql:3306/g' $$sql_file;
          # sed -i 's/jdbc:mysql:\/\/localhost:3306/jdbc:mysql:\/\/mysql:3306/g' $$sql_file;
          # sed -i 's/jdbc:redis:\/\/127.0.0.1:6379/jdbc:redis:\/\/redis:6379/g' $$sql_file;
          # sed -i 's/jdbc:redis:\/\/localhost:6379/jdbc:redis:\/\/redis:6379/g' $$sql_file;
          # sed -i 's/localhost:9001/snowy-actuator-app:9001/g' $$sql_file;
          # sed -i 's/localhost:9002/snowy-sentinel-app:9002/g' $$sql_file;
        fi;
        mysql -hmysql.cloud -P3306 -uroot -p123456 --ssl=0  < $$sql_file;
        echo '执行sql文件：$$sql_file 结束';
      done
      # 建立kong路由
      export PGPASSWORD=kong;
      cat << EOF | psql -h pgsql -U kong -d kong
      INSERT INTO "public"."services" ("id", "created_at", "updated_at", "name", "retries", "protocol", "host", "port", "path", "connect_timeout", "write_timeout", "read_timeout", "tags", "client_certificate_id", "tls_verify", "tls_verify_depth", "ca_certificates", "ws_id", "enabled") VALUES ('c5f3350e-5acb-490a-a2eb-1e3c91ebb6f4', '2025-01-12 08:17:35+00', '2025-01-12 08:41:28+00', 'gateway-service', 5, 'http', 'snowy-gateway-app', 9003, '/api/', 60000, 60000, 60000, '{}', NULL, NULL, NULL, NULL, '834eec81-a91b-40ee-9782-1acd37517dbe', 't');
      INSERT INTO "public"."services" ("id", "created_at", "updated_at", "name", "retries", "protocol", "host", "port", "path", "connect_timeout", "write_timeout", "read_timeout", "tags", "client_certificate_id", "tls_verify", "tls_verify_depth", "ca_certificates", "ws_id", "enabled") VALUES ('43f5fe41-8290-4e87-934f-2b16a9a80e3b', '2025-01-12 05:26:44+00', '2025-01-12 09:05:33+00', 'web-front', 5, 'http', 'snowy-front-web', 8080, '/', 60000, 60000, 60000, '{}', NULL, NULL, NULL, NULL, '834eec81-a91b-40ee-9782-1acd37517dbe', 't');  
      INSERT INTO "public"."routes" ("id", "created_at", "updated_at", "name", "service_id", "protocols", "methods", "hosts", "paths", "snis", "sources", "destinations", "regex_priority", "strip_path", "preserve_host", "tags", "https_redirect_status_code", "headers", "path_handling", "ws_id", "request_buffering", "response_buffering") VALUES ('baec2eb0-1769-4a63-a5a6-2ea8980420bd', '2025-01-12 08:18:21+00', '2025-01-12 08:32:49+00', 'gateway', 'c5f3350e-5acb-490a-a2eb-1e3c91ebb6f4', '{http,https}', NULL, NULL, '{/api}', NULL, NULL, NULL, 0, 'f', 'f', NULL, 426, NULL, 'v1', '834eec81-a91b-40ee-9782-1acd37517dbe', 't', 't');
      INSERT INTO "public"."routes" ("id", "created_at", "updated_at", "name", "service_id", "protocols", "methods", "hosts", "paths", "snis", "sources", "destinations", "regex_priority", "strip_path", "preserve_host", "tags", "https_redirect_status_code", "headers", "path_handling", "ws_id", "request_buffering", "response_buffering") VALUES ('c5f28824-50fd-4960-92cf-c47356d6bc03', '2025-01-12 05:32:58+00', '2025-01-12 09:06:14+00', 'web', '43f5fe41-8290-4e87-934f-2b16a9a80e3b', '{http,https}', NULL, NULL, '{/}', NULL, NULL, NULL, 0, 'f', 'f', NULL, 426, NULL, 'v1', '834eec81-a91b-40ee-9782-1acd37517dbe', 't', 't');
      EOF
      "
    networks:
      - cloud
    restart: "no"
    container_name: importSql
  snowy-nacos-app:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nacos/nacos-server:v2.4.3
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      MYSQL_SERVICE_HOST: "mysql"
      MYSQL_SERVICE_DB_NAME: "snowy-nacos-app"
      MYSQL_SERVICE_DB_PARAM: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC"
      MYSQL_SERVICE_USER: "root"
      MYSQL_SERVICE_PASSWORD: "123456"
      SPRING_DATASOURCE_PLATFORM: "mysql"
    networks:
      - cloud
    depends_on:
      - importSql
    container_name: snowy-nacos-app
    stdin_open: true
    tty: true
  snowy-gateway-app:
    image: registry.cn-hangzhou.aliyuncs.com/jp-java/snowy-gateway-app:1.0.1
    ports:
      - "9003:9003"
    environment:
      NACOS_SERVER: "snowy-nacos-app:8848"
    networks:
      - cloud
    depends_on:
      - snowy-nacos-app
    container_name: snowy-gateway-app
    stdin_open: true
    tty: true
  snowy-sentinel-app:
    image: registry.cn-hangzhou.aliyuncs.com/jp-java/snowy-sentinel-app:1.0.1
    ports:
      - "9002:9002"
    environment:
      NACOS_SERVER: "snowy-nacos-app:8848"
    networks:
      - cloud
    depends_on:
      - snowy-nacos-app
    container_name: snowy-sentinel-app
    stdin_open: true
    tty: true
  snowy-actuator-app:
    image: registry.cn-hangzhou.aliyuncs.com/jp-java/snowy-actuator-app:1.0.1
    ports:
      - "9001:9001"
    environment:
      NACOS_SERVER: "snowy-nacos-app:8848"
    networks:
      - cloud
    depends_on:
      - snowy-nacos-app
    container_name: snowy-actuator-app
    stdin_open: true
    tty: true
  snowy-biz-app:
    image: registry.cn-hangzhou.aliyuncs.com/jp-java/snowy-biz-app:1.0.1
    ports:
      - "9102:9102"
    environment:
      NACOS_SERVER: "snowy-nacos-app:8848"
    networks:
      - cloud
    depends_on:
      - snowy-nacos-app
      - redis
    container_name: snowy-biz-app
    stdin_open: true
    tty: true
  snowy-web-app:
    image: registry.cn-hangzhou.aliyuncs.com/jp-java/snowy-web-app:1.0.1
    ports:
      - "9101:9101"
    environment:
      NACOS_SERVER: "snowy-nacos-app:8848"
    networks:
      - cloud
    depends_on:
      - snowy-nacos-app
      - redis
    container_name: snowy-web-app
    stdin_open: true
    tty: true
  snowy-xxl-jpb-app:
    image: registry.cn-hangzhou.aliyuncs.com/jp-java/snowy-xxl-job-app:1.0.1
    ports:
      - "9004:9004"
    environment:
      NACOS_SERVER: "snowy-nacos-app:8848"
    networks:
      - cloud
    depends_on:
      - snowy-nacos-app
    container_name: snowy-xxl-jpb-app
    stdin_open: true
    tty: true
  snowy-front-web:
    image: registry.cn-hangzhou.aliyuncs.com/jp-java/snowy-front-web:1.0.1
    ports:
      - "8080:8080"
    networks:
      - cloud
    container_name: snowy-front-web
    stdin_open: true
    tty: true
