{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := .Values.fullnameOverride | default (printf "%s-%s" .Release.Name $name) | trunc 63 | trimSuffix "-" }}
{{- if and .Values.enabled .Values.components.gateway }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-gateway-nginx
  labels:
    app.kubernetes.io/name: {{ quote $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
data:
  default.conf: |
    server {
      listen {{ .Values.gateway.listenPort }};
      server_name _;
      client_max_body_size 100m;

      if ($request_method = OPTIONS) {
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods 'GET,POST,OPTIONS,PUT,PATCH,DELETE' always;
        add_header Access-Control-Allow-Headers * always;
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 204;
      }

      add_header Access-Control-Allow-Origin * always;
      add_header Access-Control-Allow-Methods 'GET,POST,OPTIONS,PUT,PATCH,DELETE' always;
      add_header Access-Control-Allow-Headers * always;

      location /healthz {
        default_type text/plain;
        return 200 'ok';
      }

      {{- if .Values.components.auth }}

      location /auth/v1/ {
        proxy_pass http://{{ $fullname }}-auth:9999/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      {{- end }}

      {{- if .Values.components.rest }}

      location /rest/v1/ {
        proxy_pass http://{{ $fullname }}-rest:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
      }
      {{- end }}

      {{- if .Values.components.realtime }}

      location /realtime/v1/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass http://{{ $fullname }}-realtime:4000/socket/;
      }
      {{- end }}
    }

{{- end }}
