{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := .Values.fullnameOverride | default (printf "%s-%s" .Release.Name $name) | trunc 63 | trimSuffix "-" }}
{{- if and .Values.enabled (eq .Values.gateway.mode "kong") (.Values.gateway.kong.useComposePrep | default true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-kong-entry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ quote $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kong
data:
  kong-entrypoint.sh: |
{{ .Files.Get "files/kong/kong-entrypoint.sh" | nindent 4 }}
{{- end }}
