{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := .Values.fullnameOverride | default (printf "%s-%s" .Release.Name $name) | trunc 63 | trimSuffix "-" }}
{{- $g := .Values.gateway.kong }}
{{- if and .Values.enabled (eq .Values.gateway.mode "kong") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-kong-proxy
  labels:
    app.kubernetes.io/name: {{ quote $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kong-proxy
spec:
  type: {{ $g.service.proxy.type }}
  ports:
    - port: {{ $g.service.proxy.port }}
      targetPort: {{ $g.service.proxy.targetPort }}
      protocol: TCP
      name: proxy
  selector:
    app.kubernetes.io/name: {{ quote $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kong
{{- end }}
