{{- if .Values.createSecrets -}}
## JWT Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-jwt
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  anonKey: {{ .Values.secret.jwt.anonKey | b64enc | quote }}
  serviceKey: {{ .Values.secret.jwt.serviceKey | b64enc | quote }}
  secret: {{ .Values.secret.jwt.secret | b64enc | quote }}
---
## Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secret.db.password | b64enc | quote }}
  database: {{ .Values.secret.db.database | b64enc | quote }}
---
## Analytics Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-analytics
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  publicAccessToken: {{ .Values.secret.analytics.publicAccessToken | b64enc | quote }}
  privateAccessToken: {{ .Values.secret.analytics.privateAccessToken | b64enc | quote }}
---
## SMTP Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-smtp
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secret.smtp.username | b64enc | quote }}
  password: {{ .Values.secret.smtp.password | b64enc | quote }}
---
## Dashboard Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-dashboard
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secret.dashboard.username | b64enc | quote }}
  password: {{ .Values.secret.dashboard.password | b64enc | quote }}
  openAiApiKey: {{ .Values.secret.dashboard.openAiApiKey | b64enc | quote }}
---
## S3 Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  keyId: {{ .Values.secret.s3.keyId | b64enc | quote }}
  accessKey: {{ .Values.secret.s3.accessKey | b64enc | quote }}
---
## Realtime Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-realtime
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  secretKeyBase: {{ .Values.secret.realtime.secretKeyBase | b64enc | quote }}
---
## Meta Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-meta
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  cryptoKey: {{ .Values.secret.meta.cryptoKey | b64enc | quote }}
---
## MinIO Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-minio
  namespace: {{ .Release.Namespace }}
  labels: {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.secret.minio.user | b64enc | quote }}
  password: {{ .Values.secret.minio.password | b64enc | quote }}
{{- end }}
