{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meta.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "meta.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "meta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "meta.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "meta.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      securityContext: {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ include "meta.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_USER
              value: {{ .Values.environment.DB_USER | quote }}
            - name: DB_DRIVER
              value: {{ .Values.environment.DB_DRIVER | quote }}
            - name: DB_SSL
              value: {{ .Values.environment.DB_SSL | quote }}
            - name: PG_META_PORT
              value: {{ .Values.environment.PG_META_PORT | quote }}
            {{- if .Values.dbHost }}
            - name: PG_META_DB_HOST
              value: {{ .Values.dbHost | quote }}
            {{- end }}
            {{- if .Values.dbPort }}
            - name: PG_META_DB_PORT
              value: {{ .Values.dbPort | quote }}
            {{- end }}
            {{- if .Values.dbName }}
            - name: PG_META_DB_NAME
              value: {{ .Values.dbName | quote }}
            {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-db
                  key: password
            - name: CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.fullname" . }}-meta
                  key: cryptoKey
          {{- with .Values.deployment.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.lifecycle }}
          lifecycle: {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
      {{- with .Values.deployment.volumes }}
      volumes: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
