{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := .Values.fullnameOverride | default (printf "%s-%s" .Release.Name $name) | trunc 63 | trimSuffix "-" }}
{{- $chartLabel := printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- $feFullname := printf "%s-fe" $fullname | trunc 63 | trimSuffix "-" }}
{{- $beFullname := printf "%s-be" $fullname | trunc 63 | trimSuffix "-" }}
{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $beFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "component" "be" | toYaml | nindent 4 }}
spec:
  serviceName: {{ $beFullname }}
  replicas: {{ .Values.be.replicas }}
  selector:
    matchLabels:
{{- dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "component" "be" | toYaml | nindent 6 }}
  template:
    metadata:
      {{- with .Values.be.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
{{- dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "component" "be" | toYaml | nindent 8 }}
    spec:
      {{- with .Values.be.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      {{- with .Values.be.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.be.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.be.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.be.podSecurityContext | nindent 8 }}
      containers:
        - name: be
          securityContext:
            {{- toYaml .Values.be.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.be_tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - /opt/apache-doris/be/bin/start_be.sh --daemon && tail -f /opt/apache-doris/be/log/be.log
          ports:
            - name: rpc
              containerPort: 9060
              protocol: TCP
            - name: web
              containerPort: 8040
              protocol: TCP
            - name: heartbeat
              containerPort: 9050
              protocol: TCP
          env:
            - name: BE_HOME
              value: /opt/apache-doris/be
            - name: FE_HOST
              value: {{ $feFullname }}
          volumeMounts:
            - name: be-data
              mountPath: /opt/apache-doris/be/storage
          resources:
            {{- toYaml .Values.be.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: be-data
      spec:
        accessModes:
          - {{ .Values.be.persistence.accessMode | default "ReadWriteOnce" }}
        {{- if .Values.be.persistence.storageClass }}
        {{- if (eq "-" .Values.be.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.be.persistence.storageClass }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.be.persistence.size | default "10Gi" }}
{{- end }}
