{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := .Values.fullnameOverride | default (printf "%s-%s" .Release.Name $name) | trunc 63 | trimSuffix "-" }}
{{- $chartLabel := printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- $feFullname := printf "%s-fe" $fullname | trunc 63 | trimSuffix "-" }}
{{- $beFullname := printf "%s-be" $fullname | trunc 63 | trimSuffix "-" }}
{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $feFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "component" "fe" | toYaml | nindent 4 }}
  {{- with .Values.fe.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.fe.service.type }}
  ports:
    - port: {{ .Values.fe.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.fe.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.fe.service.queryPort }}
      targetPort: query
      protocol: TCP
      name: query
  selector:
{{- dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "component" "fe" | toYaml | nindent 4 }}
{{- end }}
