{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db.fullname" . }}-initdb
  labels: {{- include "db.labels" . | nindent 4 }}
data:
  99-jwt.sql: |
{{ .Files.Get "files/jwt.sql" | indent 4 }}
  99-realtime.sql: |
{{ .Files.Get "files/realtime.sql" | indent 4 }}
  99-roles.sql: |
{{ .Files.Get "files/roles.sql" | indent 4 }}
  98-webhooks.sql: |
{{ .Files.Get "files/webhooks.sql" | indent 4 }}
{{- end }}
