{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "db.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "db.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "db.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "db.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      securityContext: {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      initContainers:
        - name: init-db
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              cp /docker-entrypoint-initdb.d/* /initdb.d/
          volumeMounts:
            - mountPath: /initdb.d
              name: initdb-scripts
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb-scripts-source
              readOnly: true
      containers:
        - name: {{ include "db.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: /var/run/postgresql
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            {{- if .Values.dbSecretRef }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretRef }}
                  key: password
            {{- end }}
            {{- if .Values.jwtSecretRef }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwtSecretRef }}
                  key: secret
            {{- end }}
            {{- if .Values.analyticsSecretRef }}
            - name: LOGFLARE_PUBLIC_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.analyticsSecretRef }}
                  key: publicAccessToken
            {{- end }}
          {{- with .Values.deployment.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.deployment.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - mountPath: /var/lib/postgresql/data
              name: db-data
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb-scripts
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.lifecycle }}
          lifecycle: {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
      volumes:
        - name: initdb-scripts
          emptyDir: {}
        - name: initdb-scripts-source
          configMap:
            name: {{ include "db.fullname" . }}-initdb
            defaultMode: 0755
        {{- with .Values.deployment.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: db-data
        labels: {{- include "db.selectorLabels" . | nindent 10 }}
      spec:
        {{- $sc := .Values.persistence.storageClassName | default .Values.global.defaultStorageClassName }}
        {{- if $sc }}
        storageClassName: {{ $sc }}
        {{- end }}
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
    {{- else }}
    - metadata:
        name: db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    {{- end }}
{{- end }}
