annotations:
  catalog.cattle.io/release-name: &jenkins jenkins
apiVersion: v2
name: *jenkins
version: 1.0.8
icon: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/jenkins/jenkins-original.svg
description: A Helm chart for deploying the kafka application
type: application
keywords:
  - *jenkins
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@163.com
appVersion: "1.0.1"
