user: admin
password: 123456

service:
  port: 8080

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: jenkins.example.com
      paths:
        - path: /
          pathType: Prefix
