apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{.Chart.Name}}
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 31092
      name: kafka-9092
    - protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 31093
      name: kafka-9093
  type: NodePort
  