apiVersion: v1
kind: Service
metadata:
  name: snowy-biz-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: snowy-biz-app
  ports:
    - protocol: TCP
      name: biz-9102
      port: 9102
      targetPort: 9102
  type: ClusterIP
  