apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowy-front-web-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Release.Namespace}}.jiapeng.icu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snowy-front-web
                port:
                  number: 80