apiVersion: v1
kind: Service
metadata:
  name: snowy-nacos-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: snowy-nacos-app
  ports:
    - protocol: TCP
      name: nacos-8848
      port: 8848
      targetPort: 8848
    - protocol: TCP
      name: nacos-9848
      port: 9848
      targetPort: 9848
    - protocol: TCP
      name: nacos-9849
      port: 9849
      targetPort: 9849
  type: ClusterIP
  