{{- /* Check if the "server" namespace already exists */}}
{{- if not (lookup "v1" "Namespace" "" "server") }}
apiVersion: v1
kind: Namespace
metadata:
  name: server  {{- /* 创建名为 "server" 的命名空间 */}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
{{- end }}
{{- /* Check if the mysql Service already exists in the "server" namespace */}}
{{- if and (not (lookup "v1" "Service" "server" "mysql")) .Values.global.server.mysql.hostIp }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: server
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
spec:
  type: ClusterIP
  ports:
    - port: 3306  # Service 暴露的端口
      targetPort: 3306  # 外部 MySQL 服务的端口
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: server
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
subsets:
  - addresses:
      - ip: {{.Values.global.server.mysql.hostIp}}  # 外部 MySQL 服务的 IP 地址
    ports:
      - port: 3306  # 外部 MySQL 服务的端口
{{- end }}
{{- /* Check if the redis Service already exists in the "server" namespace */}}
{{- if and (not (lookup "v1" "Service" "server" "redis")) .Values.global.server.redis.hostIp }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: server  {{- /* Hardcode the namespace to "server" */}}
  labels:
    app: redis
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
spec:
  type: ClusterIP
  ports:
    - port: 6379  {{- /* Redis default port */}}
      targetPort: 6379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: server
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
subsets:
  - addresses:
      - ip: {{.Values.global.server.redis.hostIp}}  # 外部 MySQL 服务的 IP 地址
    ports:
      - port: 6379  # 外部 MySQL 服务的端口
{{- end }}