{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := .Values.fullnameOverride | default (printf "%s-%s" .Release.Name $name) | trunc 63 | trimSuffix "-" }}
{{- $masterHostname := printf "%s-master" $fullname | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $masterHostname }}
spec:
  type: ClusterIP
  ports:
    - port: 5557
      targetPort: comm
      name: comm
    - port: 8089
      targetPort: web
      name: web
  selector:
    {{- dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "app.kubernetes.io/component" "master" | toYaml | nindent 4 }}
