annotations:
  catalog.cattle.io/release-name: mysql
apiVersion: v2
name: mysql-new
version: 5.7.0
appVersion: "5.7"
description: A Helm chart for MySQL Database
keywords:
  - mysql
  - database
home: https://www.mysql.com/
sources:
  - https://github.com/mysql/mysql-server
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@126.com
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png