image:
  repository: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/apache/rocketmq
  tag: "5.3.2"
  pullPolicy: IfNotPresent

namesrv:
  enabled: true

broker:
  enabled: true
  javaOptsMemory: "-Xms512M -Xmx512M"

persistence:
  broker:
    enabled: false
    size: 20Gi

resources:
  broker: {}
