apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_APPLICATION_NAME
              value: "{{ .Values.application.name }}"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "{{ .Values.application.contextPath }}"
            - name: JVM_OPTS
              value: "{{ .Values.application.jvmOpts }}"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: {{ if eq .Values.database.type "h2" }}org.h2.Driver{{ else if eq .Values.database.type "mysql" }}com.mysql.cj.jdbc.Driver{{ else if eq .Values.database.type "postgresql" }}org.postgresql.Driver{{ end }}
            - name: SPRING_DATASOURCE_URL
              value: {{ if eq .Values.database.type "h2" }}jdbc:h2:file:/root/.halo2/db/halo{{ else if .Values.database.url }}{{ .Values.database.url }}{{ else if eq .Values.database.type "mysql" }}jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai{{ else if eq .Values.database.type "postgresql" }}jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?sslmode=disable{{ end }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ if not (eq .Values.database.type "h2") }}{{ .Values.database.user }}{{ end }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ if not (eq .Values.database.type "h2") }}{{ .Values.database.password }}{{ end }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.application.contextPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.application.contextPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: halo-storage
              mountPath: /root/.halo2
      volumes:
        - name: halo-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}
