apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- with .Values.consoleService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.consoleService.type }}
  ports:
    - port: {{ .Values.consoleService.port }}
      targetPort: console
      protocol: TCP
      name: console
      {{- if and (or (eq .Values.consoleService.type "NodePort") (eq .Values.consoleService.type "LoadBalancer")) .Values.consoleService.nodePort }}
      nodePort: {{ .Values.consoleService.nodePort }}
      {{- end }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
