annotations:
  catalog.cattle.io/release-name: elasticsearch
apiVersion: v2
name: elasticsearch
version: 1.0.1
icon: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/elasticsearch/elasticsearch-original.svg
description: A Helm chart for deploying the elasticsearch application
type: application
keywords:
  - elasticsearch
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@126.com
appVersion: "7.17.6"
