annotations:
  catalog.cattle.io/release-name: &appName mongodb
apiVersion: v2
name: *appName
version: 1.0.6
description: A Helm chart for deploying the kafka application
type: application
keywords:
  - *appName
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@126.com
icon: https://img2.baidu.com/it/u=452507761,625109803&fm=253&fmt=auto&app=138&f=JPEG?w=614&h=472
appVersion: "1.0.1"