annotations:
  catalog.cattle.io/release-name: &appName mongodb
apiVersion: v2
name: *appName
version: 1.0.6
icon: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/mongodb/mongodb-original.svg
description: A Helm chart for deploying the kafka application
type: application
keywords:
  - *appName
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@126.com
appVersion: "1.0.1"