annotations:
  catalog.cattle.io/release-name: nginx-ingress-controller
apiVersion: v2
name: nginx-ingress
version: 1.0.2
icon: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/nginx/nginx-original.svg
description: A nginx ingress controller
type: application
keywords:
  - nginx-ingress
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@126.com
appVersion: "1.0.1"
