annotations:
  catalog.cattle.io/release-name: kafka
apiVersion: v2
name: kafka
version: 1.0.2
icon: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/apachekafka/apachekafka-original.svg
description: A Helm chart for deploying the kafka application
type: application
keywords:
  - kafka
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@163.com
appVersion: "4.0.0"
