{{- if .Values.frps.enabled }}
{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := .Values.fullnameOverride | default (printf "%s-%s" .Release.Name $name) | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-frps" $fullname }}
  labels:
{{- dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "app.kubernetes.io/component" "frps" | toYaml | nindent 4 }}
  {{- with .Values.frps.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frps.service.type }}
  ports:
    - name: peer
      port: {{ int .Values.frps.service.ports.peer.port }}
      protocol: TCP
      targetPort: peer
      {{- if and (eq .Values.frps.service.type "NodePort") .Values.frps.service.ports.peer.nodePort }}
      nodePort: {{ int .Values.frps.service.ports.peer.nodePort }}
      {{- end }}
    {{- $vh := int .Values.frps.vhostHTTPPort }}
    {{- if gt $vh 0 }}
    - name: vhost-http
      port: {{ $vh }}
      protocol: TCP
      targetPort: vhost-http
      {{- if and (eq .Values.frps.service.type "NodePort") .Values.frps.service.vhostHTTPNodePort }}
      nodePort: {{ int .Values.frps.service.vhostHTTPNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.frps.dashboard.enabled }}
    - name: dashboard
      port: {{ int .Values.frps.service.ports.dashboard.port }}
      protocol: TCP
      targetPort: dashboard
      {{- if and (eq .Values.frps.service.type "NodePort") .Values.frps.service.ports.dashboard.nodePort }}
      nodePort: {{ int .Values.frps.service.ports.dashboard.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "app.kubernetes.io/component" "frps" | toYaml | nindent 4 }}
{{- end }}
