{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "meta.fullname" . }}
  labels: {{- include "meta.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
  selector: {{- include "meta.selectorLabels" . | nindent 4 }}
{{- end }}
