apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  mysql.cnf: |
    [mysqld]
    {{- range $key, $value := .Values.mysql.extraConfig }}
    {{ $key }} = {{ $value }}
    {{- end }}
