annotations:
  catalog.cattle.io/release-name: elasticsearch
apiVersion: v2
name: elasticsearch
version: 2.0.11
icon: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/helm/helm-original.svg
description: A Helm chart for deploying the elasticsearch application
type: application
keywords:
  - elasticsearch
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@163.com
appVersion: "8.17.3"
