## Rest (PostgREST) sub-chart values
enabled: true
replicaCount: 1

image:
  repository: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/postgrest/postgrest
  pullPolicy: IfNotPresent
  tag: "v14.8"
  pullSecrets: []

initDbImage:
  repository: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/postgres
  pullPolicy: IfNotPresent
  tag: "15-alpine"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  protocol: TCP
  portName: http
  annotations: {}

environment:
  DB_USER: authenticator
  DB_DRIVER: postgres
  DB_SSL: disable
  PGRST_DB_SCHEMAS: public,storage,graphql_public
  PGRST_DB_ANON_ROLE: anon
  PGRST_DB_USE_LEGACY_GUCS: false
  PGRST_APP_SETTINGS_JWT_EXP: 3600

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

deployment:
  annotations: {}
  podAnnotations: {}
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 30
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: ""
  envFrom: []
  volumeMounts: []
  volumes: []
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  lifecycle: {}

# Cross-component references (explicit)
dbSecretRef: ""
dbHost: ""
dbPort: ""
dbName: ""
jwtSecretRef: ""
apikeySecretRef: ""
