{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $fullname := .Values.fullnameOverride | default (printf "%s-%s" .Release.Name $name) | trunc 63 | trimSuffix "-" }}
{{- $chartLabel := printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- $feFullname := printf "%s-fe" $fullname | trunc 63 | trimSuffix "-" }}
{{- $beFullname := printf "%s-be" $fullname | trunc 63 | trimSuffix "-" }}
{{- if and .Values.enabled .Values.fe.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $feFullname }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.fe.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.fe.persistence.storageClass }}
  {{- if (eq "-" .Values.fe.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.fe.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.fe.persistence.size | default "10Gi" }}
{{- end }}
