annotations:
  catalog.cattle.io/release-name: redis
apiVersion: v2
name: redis
version: 1.0.1
icon: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/redis/redis-original.svg
description: A Helm chart for deploying the mysql application
type: application
keywords:
  - redis
home: https://example.com/snowy
sources:
  - https://github.com/your-repo/snowy
maintainers:
  - name: 贾鹏
    email: jiapeng_aoa@126.com
appVersion: "1.0.1"
