## Meta sub-chart values
enabled: true
replicaCount: 1

image:
  repository: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/supabase/postgres-meta
  pullPolicy: IfNotPresent
  tag: "v0.96.3"
  pullSecrets: []

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
  portName: http
  annotations: {}

environment:
  DB_USER: supabase_admin
  DB_DRIVER: postgres
  DB_SSL: disable
  PG_META_PORT: "8080"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

deployment:
  annotations: {}
  podAnnotations: {}
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 30
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: ""
  envFrom: []
  volumeMounts: []
  volumes: []
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  lifecycle: {}

# Cross-component references (explicit)
dbSecretRef: ""
dbHost: ""
dbPort: ""
dbName: ""
metaCryptoKeySecretRef: ""
